carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove')
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('address', views.address, name='address'),
    path('select/address', views.select_address, name='select_address'),
    path('set/address/<int:pk>', views.check_address, name='check_address'),
    path('confirm', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('complete', views.complete, name='complete'),
    path('completed', views.OrderListView.as_view(), name='completeds')
    
]

shipping_addresses/urls.py
from django.urls import path
from . import views

app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('new', views.create, name='create'),
    path('update/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default')
]

store/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
from products.views import ProductListView
from . import views

urlpatterns = [
    path('', ProductListView.as_view(), name="index"),
    path('users/login', views.login_view, name="login"),
    path('users/logout', views.logout_view, name="logout"),
    path('users/register', views.register, name="register"),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('cart/', include('carts.urls')),
    path('order/', include('orders.urls')),
    path('address/', include('shipping_addresses.urls')),
    path('code/', include('promo_codes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>{{ title }}</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
       
    </head>
    <body>
        {% include 'navbar.html' %}

        <div class="container">
           {% include 'messages.html' %}
           
           {% block  breadcrumb %}
           {% endblock %}
            <div class="row mt-5">
                

                {% block content %}
                {% endblock %}
            </div>
        </div>
    </body>
    <script src="https://kit.fontawesome.com/2518860693.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}" ></script>
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>

    {% block javascript %}
    {% endblock %}
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
        <div class="col">
            <h4 class="text-center">{{ message }}</h4>
            {% include 'products/snippets/search.html' %}
            {% include 'products/snippets/list.html' %}
            
        </div>
{% endblock %}

templates/messages.html
{% if messages %}
{% for message in messages%}
<div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %}">
    <button type="button" class="close" data-dismiss="alert">x</button>
    {{ message }}
</div>
{%endfor%}
{% endif %}

templates/navbar.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'carts:cart' as cart %}
{% url 'shipping_addresses:shipping_addresses' as shipping_addresses %}
{% url 'orders:completeds' as completeds %}


<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a href="{% url 'index' %}" class="navbar-brand">Store</a>
    <button type="button" name="button"  class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navb">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div id="#navb" class="navbar-collapse collapse hide">
        <ul class="navbar-nav">
            
            <li class="nav-item {% if request.path == cart %}active {% endif %}">
                <a class="nav-link" href="{{ cart }}">  <span class="fa fa-shopping-cart"></span> My cart</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item {% if request.path == shipping_addresses %}active {% endif %}">
                <a class="nav-link" href="{{ shipping_addresses }}">  <span class="fa fa-location-arrow"></span> My address</a>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="nav-item {% if request.path == completeds %}active {% endif %}">
                <a class="nav-link" href="{{ completeds }}">  <span class="fa fa-shipping-fast"></span> My orders</a>
            </li>
            {% endif %}
        </ul>



        <ul class="nav navbar-nav ml-auto">

            {% if user.is_authenticated %}
                <li class="navbar-item {% if request.path == logout %}active {% endif %}">
                    <a href="{% url 'logout' %}" class="nav-link">
                        <span class="fa fa-sign-in-alt"></span>
                        Logout</a>
                </li>
            {% else %}
            <li class="navbar-item {% if request.path == login %}active {% endif %}">
                <a href="{{ login }}" class="nav-link">
                    <span class="fa fa-user"></span>
                    Login</a>
            </li>
            <li class="navbar-item {% if request.path == register %}active {% endif %}">
                <a href="{{ register }}" class="nav-link">
                    <span class="fa fa-user-plus"></span>
                    Registro</a>
            </li>
            {% endif %}


        </ul>
    </div>
</nav> 